config/routes.rb
OauthProviderApplication::Application.routes.draw do
  use_doorkeeper

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :profiles
      resources :users
      get '/me' => "credentials#me"
      get '/fast' => 'fast#index'
    end
  end

  get "/users/sign_up" => "users#new"
  post "/user" => "users#create"

  root :to => "login#index"
end

app/models/api/user.rb
module Api
  class User < Apollo
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable,
  # :timeoutable, :trackable, :registerable, :recoverable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  def self.blacklist_keys
    @blacklist_keys ||= super - ["id"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
class LoginController < ActionController::Base
  protect_from_forgery
  def index
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create!(params[:user])
    sign_in_and_redirect @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OauthProviderApplication</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<%= form_for(@user, :url => user_path(@user)) do |f| %>
  <div class="clearfix">
    <%= f.label :username %>
    <div class="input">
      <%= f.email_field :username %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :password %>
    <div class="input">
      <%= f.password_field :password %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Sign in", :class => "btn btn-primary" %><small> or <%=link_to "Sign Up", users_sign_up_path %></small>
  </div>
<% end %>